export type Language = "en" | "zh";

export const INSTALL_COMMAND = "npx skills add juju-w/safa --skill safa";
export const GITHUB_URL = "https://github.com/juju-w/safa";

export function siteHref(path = "") {
  return `${import.meta.env.BASE_URL}${path}`;
}

export const homeCopy = {
  en: {
    navProduct: "Product",
    navSecurity: "Security",
    navHow: "How it works",
    heroEyebrow: "Infrastructure diagnostics without secret sharing",
    heroSlogan: "Let your AI agent diagnose servers—without giving it your credentials.",
    heroAcronym: "Secure Access for Agents",
    heroBody: "Register a machine once on your Mac. Then ask naturally: “Why is production down?” SAFA finds the right resource, checks its topology, asks for your approval, and returns bounded evidence.",
    github: "View on GitHub",
    seeDemo: "See a real diagnosis",
    readArticle: "Read",
    allDocs: "All documentation",
    articlesEyebrow: "Deep dives",
    articlesTitle: "From the blog",
    articles: [
      { title: "Why Your AI Agent Should Never Hold Your SSH Keys", summary: "Agents are doing ops now — and handing them a key is exactly the wrong move. Process separation, allow-list policy, and user-presence authorization, with real evidence. · 中文版", url: "why-safa/", date: "2026-08-19" },
      { title: "The SAFA Access Pattern: Every Resource, Topology, No Plaintext Password", summary: "How hosts, databases, object storage, caches, and services are registered with credentials that never become plaintext; trusted-setup password entry; jump routes and pinned identity; topology from evidence. · 中文版", url: "why-safa/access-patterns/", date: "2026-08-19" },
    ],
    learnHow: "How SAFA works",
    whySafa: "Why SAFA",
    install: "Source preview",
    copied: "Copied",
    copyInstall: "Copy install command",
    switchLanguage: "Switch language to",
    mascotAlt: "SAFA owl guardian",
    promptEyebrow: "Ask normally",
    promptTitle: "No IP hunt. No password handoff. Just describe the problem.",
    promptBody: "SAFA gives the Agent safe aliases and verified relationships, so it can plan a useful diagnostic without making you translate your infrastructure into connection details.",
    promptItems: [
      {
        prompt: "Why is the production API returning 502?",
        result: "Find the service, verify its host, and inspect bounded health evidence.",
      },
      {
        prompt: "Can the crawler reach MySQL from this node?",
        result: "Ask the Broker for a verified path instead of guessing from IPs.",
      },
      {
        prompt: "What breaks if the NAS goes down?",
        result: "Compute the affected services from the dependency graph.",
      },
    ],
    userLabel: "You",
    demoTitle: "Diagnose checkout-api",
    online: "Online",
    conversation: "Conversation",
    session: "Session · interactive demo",
    userPrompt: "Why is checkout-api returning 502? Diagnose only—don’t change anything.",
    thinking: "Working through SAFA…",
    discovered: "Discovered resource alias",
    topology: "Checked topology",
    topologyDetail: "checkout-api · production",
    health: "Ran safe health check",
    authorization: "Authorization required",
    authorizationBody: "A read-only action needs your approval.",
    resource: "Resource",
    action: "Action",
    actionValue: "Read service logs from the last 10 minutes",
    scope: "Scope",
    scopeValue: "One action · expires in 5 minutes",
    sealed: "Credentials stay on this Mac",
    touchId: "Authorize with Touch ID",
    waiting: "Waiting for your authorization…",
    granted: "Authorization granted",
    logRead: "Executed log read",
    logReadDetail: "Last 10 minutes · read-only",
    finding: "Finding",
    findingValue: "Database connection pool exhausted. No changes made.",
    message: "Message SAFA Agent…",
    policy: "Policy active",
    leastPrivilege: "Least privilege",
    replay: "Replay demo",
    liveSessionTitle: "See the real session",
    liveSessionBody: "Every step below really ran against a registered resource on a real Mac — through the signed Runtime, with the actual TOON evidence. No script, no mock.",
    liveSessionCta: "Open the live demo",
    trustEyebrow: "Security boundary",
    trustTitle: "The Agent gets the answer. Your Mac keeps the credentials.",
    trustBody: "SAFA turns a natural-language request into one policy-checked operation. The password or private key never becomes model input, tool output, or chat history.",
    requestTitle: "Agent names the task",
    requestBody: "It asks for a logical resource and a bounded action—not an IP, username, or key.",
    policyTitle: "SAFA resolves and authorizes",
    policyBody: "The native Runtime finds the protected route and credential, enforces policy, and asks for user presence when needed.",
    resourceTitle: "Only the action runs",
    resourceBody: "The target receives the approved operation; the Agent receives bounded, sanitized evidence.",
    credentials: "Passwords, private keys, tokens, and vault keys never enter the Agent-visible channel.",
    openTitle: "Open source, security boundary included.",
    openBody: "Review the Skill, public contract, topology model, and native Runtime architecture.",
    footer: "Secure Access for Agents",
  },
  zh: {
    navProduct: "产品",
    navSecurity: "安全机制",
    navHow: "工作原理",
    heroEyebrow: "不用交出密码的智能运维",
    heroSlogan: "让 AI 帮你排查服务器，不必把密码交给它。",
    heroAcronym: "面向智能体的安全访问层",
    heroBody: "在 Mac 上登记一次机器，之后直接问“生产服务为什么挂了？”SAFA 会定位资源和访问路径，需要时向你请求授权，再把有限、可审计的排查证据交给智能体。",
    github: "在 GitHub 查看源码",
    seeDemo: "看一次真实排查",
    readArticle: "阅读",
    allDocs: "全部文档",
    articlesEyebrow: "深度阅读",
    articlesTitle: "文章",
    articles: [
      { title: "为什么 AI Agent 永远不该拿到你的 SSH 密钥", summary: "Agent 开始做运维了——把钥匙交给它恰恰是错的方向。进程隔离、白名单策略、用户在场授权，附真实证据。", url: "why-safa/", date: "2026-08-19" },
      { title: "SAFA 访问模式：所有资源类型、拓扑，以及不落明文的密码", summary: "主机、数据库、对象存储、缓存与服务如何统一登记且密码永不落明文；trusted-setup 安全录入；跳板与钉住身份；基于证据的拓扑答案。", url: "why-safa/access-patterns/zh/", date: "2026-08-19" },
    ],
    learnHow: "了解工作原理",
    whySafa: "为什么要做 SAFA",
    install: "源码预览",
    copied: "已复制",
    copyInstall: "复制安装命令",
    switchLanguage: "切换语言：",
    mascotAlt: "SAFA 守护猫头鹰",
    promptEyebrow: "直接说问题",
    promptTitle: "不用先找 IP，也不用把密码复制进对话。",
    promptBody: "SAFA 把安全别名和经过验证的资源关系交给智能体。你只需要描述故障，不需要先把公司的服务器拓扑翻译成一堆连接参数。",
    promptItems: [
      {
        prompt: "生产 API 为什么一直返回 502？",
        result: "定位服务和宿主机，再读取有限的健康检查证据。",
      },
      {
        prompt: "这台爬虫节点能访问 MySQL 吗？",
        result: "由本机 Broker 验证访问路径，而不是让模型猜 IP。",
      },
      {
        prompt: "NAS 挂了会影响哪些服务？",
        result: "从依赖图计算受影响范围，并返回明确结果。",
      },
    ],
    userLabel: "你",
    demoTitle: "排查 checkout-api 故障",
    online: "运行中",
    conversation: "对话",
    session: "交互演示",
    userPrompt: "checkout-api 为什么一直返回 502？只排查原因，不要修改任何配置。",
    thinking: "正在排查…",
    discovered: "定位到目标资源",
    topology: "确认服务拓扑",
    topologyDetail: "checkout-api · 生产环境",
    health: "完成只读健康检查",
    authorization: "需要你的授权",
    authorizationBody: "继续读取日志前，请确认这次只读操作。",
    resource: "目标资源",
    action: "即将执行",
    actionValue: "读取最近 10 分钟的服务日志",
    scope: "授权范围",
    scopeValue: "仅限本次操作 · 5 分钟内有效",
    sealed: "凭证只留在这台 Mac 上",
    touchId: "使用 Touch ID 授权",
    waiting: "等待授权…",
    granted: "已获得授权",
    logRead: "已读取服务日志",
    logReadDetail: "最近 10 分钟 · 只读",
    finding: "排查结果",
    findingValue: "数据库连接池已耗尽；全程未修改任何配置。",
    message: "向 SAFA Agent 提问…",
    policy: "安全策略已生效",
    leastPrivilege: "默认最小权限",
    replay: "重新播放",
    liveSessionTitle: "看一次真实会话",
    liveSessionBody: "下面每一步都真的在已登记资源上执行过——走已签名 Runtime、带真实 TOON 证据。没有脚本，没有假数据。",
    liveSessionCta: "打开真实演示",
    trustEyebrow: "安全边界",
    trustTitle: "智能体拿到排查结果，凭证仍然只在你的 Mac 上。",
    trustBody: "SAFA 把自然语言请求变成一次经过策略校验的操作。密码和私钥不会进入模型输入、工具输出或聊天记录。",
    requestTitle: "智能体只描述任务",
    requestBody: "它使用逻辑别名和有限操作，不需要知道 IP、用户名或私钥。",
    policyTitle: "SAFA 解析并授权",
    policyBody: "原生 Runtime 在本机查找访问路径和凭证、校验策略，并在必要时请求本人确认。",
    resourceTitle: "目标只执行这次操作",
    resourceBody: "服务器收到经过授权的操作；智能体只拿到经过裁剪和脱敏的证据。",
    credentials: "密码、私钥、Token 和保险箱密钥都不会进入智能体可见通道。",
    openTitle: "开源，也把安全边界讲清楚。",
    openBody: "查看 Skill、公开协议、拓扑模型和原生 Runtime 架构。",
    footer: "面向智能体的安全访问层",
  },
} as const;